_BASE_: maskformer2_R101_bs16_90k_boundary.yaml
MODEL:
  MASK_FORMER:
    BOUNDARY_DECODER:
      ENABLED: True
      QUERY_REFINEMENT: True
      HIGH_RES_ONLY: True
      TOPK_RATIO: 64
      MIN_TOPK_TOKENS: 256
      SCORE_SMOOTH_KERNEL: 7
      WARMUP_ITERS: 10000
      INIT_GATE_BIAS: -4.0
